-- Run this SQL in your Supabase SQL Editor to add missing columns for participant management

-- Add missing columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS participant_type TEXT;

-- Add status column to fishers table if not exists
ALTER TABLE fishers ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE fishers ADD COLUMN IF NOT EXISTS email TEXT;

-- Create registry table for vessels, facilities and other non-human assets
CREATE TABLE IF NOT EXISTS registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  root_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  email TEXT,
  contact_number TEXT,
  address TEXT,
  metadata JSONB DEFAULT '{}',
  status TEXT DEFAULT 'active',
  linked_user_id BIGINT,
  linked_vessel_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_registry_type ON registry(type);
CREATE INDEX IF NOT EXISTS idx_registry_status ON registry(status);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
