-- Run this SQL in your Supabase SQL Editor to set up the database

-- Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'captain', 'worker', 'public', 'inspector')),
  full_name TEXT,
  vessel_name TEXT,
  vessel_id BIGINT,
  owner_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Vessels Table
CREATE TABLE IF NOT EXISTS vessels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  registration_number TEXT UNIQUE,
  owner_name TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive'))
);

-- Trips Table
CREATE TABLE IF NOT EXISTS trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_code TEXT UNIQUE NOT NULL,
  vessel_name TEXT,
  captain_id BIGINT,
  departure_date TIMESTAMP WITH TIME ZONE,
  return_date TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  fishing_method TEXT,
  departure_port TEXT,
  crew_count INT,
  fuel_liters DECIMAL(10,2),
  fuel_price DECIMAL(10,2),
  ice_kg DECIMAL(10,2),
  ice_price DECIMAL(10,2),
  food_budget DECIMAL(10,2),
  other_expenses DECIMAL(10,2),
  total_expenses DECIMAL(10,2),
  target_species TEXT,
  expected_return_date TIMESTAMP WITH TIME ZONE,
  vessel_image TEXT,
  gear_image TEXT
);

-- Catch Logs Table
CREATE TABLE IF NOT EXISTS catch_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id BIGINT REFERENCES trips(id),
  species_name TEXT,
  weight_kg DECIMAL(10,2),
  count INT,
  quality_grade TEXT,
  freshness TEXT DEFAULT 'Excellent' CHECK (freshness IN ('Excellent', 'Good', 'Fair', 'Poor')),
  damage_assessment TEXT DEFAULT 'None' CHECK (damage_assessment IN ('None', 'Minor', 'Moderate', 'Major')),
  gps_lat DECIMAL(10,8),
  gps_lng DECIMAL(11,8),
  location_name TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  qr_code TEXT UNIQUE,
  images JSONB,
  catch_session_id TEXT,
  entered_by BIGINT,
  crate_id BIGINT,
  temperature DECIMAL(5,2),
  inspected_by BIGINT,
  inspected_at TIMESTAMP WITH TIME ZONE
);

-- Crates Table
CREATE TABLE IF NOT EXISTS crates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crate_qr TEXT UNIQUE NOT NULL,
  trip_id BIGINT REFERENCES trips(id),
  total_weight DECIMAL(10,2) DEFAULT 0,
  fish_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- QR Counters Table
CREATE TABLE IF NOT EXISTS qr_counters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qr_type TEXT,
  country_code TEXT,
  landing_centre TEXT,
  year TEXT,
  last_number INT DEFAULT 0
);

-- QR Codes Table
CREATE TABLE IF NOT EXISTS qr_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  batch_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  status TEXT DEFAULT 'generated',
  image_url TEXT
);

-- Pending Registrations Table
CREATE TABLE IF NOT EXISTS pending_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name TEXT,
  vessel_name TEXT,
  contact_info TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Default Users
INSERT INTO users (username, password, role, full_name) 
VALUES ('admin', 'fish123', 'admin', 'System Admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO users (username, password, role, full_name, vessel_name) 
VALUES ('captain1', 'fish123', 'captain', 'John Doe', 'Blue Horizon')
ON CONFLICT (username) DO NOTHING;

INSERT INTO users (username, password, role, full_name) 
VALUES ('worker1', 'fish123', 'worker', 'Jane Smith')
ON CONFLICT (username) DO NOTHING;

INSERT INTO users (username, password, role, full_name) 
VALUES ('inspector1', 'fish123', 'inspector', 'Inspector Gadget')
ON CONFLICT (username) DO NOTHING;
