-- Run this script in your Supabase SQL Editor to create the Fisher tables

-- 1. Create 'fishers' table
CREATE TABLE IF NOT EXISTS fishers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    fathers_name TEXT,
    mobile_number TEXT UNIQUE NOT NULL,
    home_port TEXT,
    address TEXT,
    emergency_contact_name TEXT,
    emergency_contact_number TEXT,
    qr_code TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT DEFAULT 'active'
);

-- 2. Create 'trip_crew' table to link trips and fishers
CREATE TABLE IF NOT EXISTS trip_crew (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT REFERENCES trips(id) ON DELETE CASCADE,
    fisher_id BIGINT REFERENCES fishers(id) ON DELETE CASCADE,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(trip_id, fisher_id)
);

-- 3. Create indexes
CREATE INDEX IF NOT EXISTS idx_fishers_mobile ON fishers(mobile_number);
CREATE INDEX IF NOT EXISTS idx_fishers_qr ON fishers(qr_code);
CREATE INDEX IF NOT EXISTS idx_trip_crew_trip ON trip_crew(trip_id);
CREATE INDEX IF NOT EXISTS idx_trip_crew_fisher ON trip_crew(fisher_id);

-- 4. Verify
SELECT count(*) FROM fishers;
SELECT count(*) FROM trip_crew;
